<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsmlgwd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsmlgwd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXsmlgwd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXsmlgwd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXsmlgwd\appProdProjectContainer([
    'container.build_hash' => 'Xsmlgwd',
    'container.build_id' => '4ebbdb7e',
    'container.build_time' => 1560328447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsmlgwd');
