<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI3hgesx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI3hgesx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerI3hgesx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerI3hgesx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerI3hgesx\appProdProjectContainer([
    'container.build_hash' => 'I3hgesx',
    'container.build_id' => '27ab4394',
    'container.build_time' => 1558668213,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI3hgesx');
