<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHtr4akw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHtr4akw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHtr4akw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHtr4akw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHtr4akw\appProdProjectContainer([
    'container.build_hash' => 'Htr4akw',
    'container.build_id' => '1b6a336b',
    'container.build_time' => 1560930914,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHtr4akw');
